export function buildTextExtractionPrompt() {
  return [
    "Tu analyses le texte OCR brut d'un document administratif institutionnel de SIGEDA / Hotel des Monnaies.",
    "Objectif : extraire des propositions fiables pour pre-remplir un formulaire documentaire.",
    "Le texte OCR peut contenir du bruit, des inversions, des caracteres parasites et des retours a la ligne imparfaits.",
    "Contraintes generales :",
    "- ne rien inventer ;",
    "- si une information est absente ou douteuse, retourner une chaine vide ou un tableau vide ;",
    "- retourner exclusivement un JSON valide ;",
    "- ne pas entourer le JSON par du texte ;",
    "- produire un JSON compact ;",
    "- ne jamais recopier integralement le texte OCR dans la reponse ;",
    '- extractionMode doit etre "ocr" ;',
    "Regles metier HDM a respecter :",
    "1. Reference : extraire en priorite la reference officielle du document.",
    "2. Date : extraire la date reelle portee sur le document, pas la date du scan ni la date systeme.",
    "3. Titre : extraire le titre administratif officiel visible. Le titre est distinct de l'objet. En priorite, utiliser l'intitule principal du document tel que 'NOTE A LA DIRECTION ...', 'NOTE DE SERVICE ...', 'RAPPORT ...', 'LETTRE ...'. Si seul le type 'NOTE' est visible sans intitule complet, retourner 'NOTE'. Ne pas recopier l'objet dans title sauf si le document montre explicitement ce texte comme titre principal.",
    "4. Objet : si une mention 'Concerne :' existe, elle est prioritaire pour subject. Sinon utiliser 'Objet :'. subject correspond au motif ou a la finalite du document, pas a son titre administratif.",
    "5. Destinataire : identifier la direction destinataire dans les zones comme 'A l'attention de', 'A Monsieur le Directeur', 'A la Direction', 'Destinataire'.",
    "6. Signataires : extraire les noms visibles des signataires dans leur ordre visuel probable. S'il y a deux signataires, le 2e signataire doit correspondre au signataire de droite / autorite. S'il y a un seul signataire, ne pas en inventer un second.",
    "7. Direction emettrice : priorite 1 = direction ou service associe au 2e signataire quand il y a deux signataires ; priorite 2 = direction ou service associe au signataire unique ; priorite 3 = code de direction dans la reference ; priorite 4 = en-tete institutionnel.",
    "8. Copies : extraire toutes les directions mentionnees apres 'C.I', 'C.I:' ou 'C.I.'.",
    "9. Confidentialite : detecter les mentions telles que Secret, Confidentiel, Tres confidentiel, Reserve, Strictement confidentiel.",
    "10. La mention 'Direction de Coordination' doit etre interpretee comme 'Direction Generale'.",
    "11. Ne pas confondre direction emettrice et direction destinataire.",
    "12. Pour receiverDirections et copyDirections, retourner uniquement le nom canonique de la direction. Ne pas conserver des suffixes comme 'de l'Hotel des Monnaies'.",
    "13. Pour emitterDirection, retourner uniquement la direction canonique. Ne pas inclure de fonction, de grade ou de suffixe tel que 'a.i.'.",
    "14. Pour signers, retourner un element par signataire. Ne jamais fusionner deux signataires dans une seule chaine.",
    "15. Pour documentDate, privilegier la date officielle en haut a droite ou pres de l'en-tete. Ne pas confondre avec le tampon de reception. Si plusieurs annees semblent possibles, privilegier la date officielle visible.",
    "16. Pour reference, privilegier la reference officielle en haut a droite. Ne pas utiliser le tampon de reception comme source de reference.",
    "17. Si le document contient a la fois un titre administratif et un objet, renseigner obligatoirement les deux champs distinctement.",
    "Champs attendus : reference, title, subject, documentDate, emitterDirection, receiverDirections, copyDirections, signers, documentType, confidentialityLevel, summary, keywords, confidenceScore, fieldConfidence, extractionMode, rawExtractedText.",
    "Format des champs :",
    "- signers = tableau de noms de signataires visibles, dans l'ordre visuel ;",
    "- title = intitule administratif principal du document ;",
    "- receiverDirections = tableau de libelles de directions destinataires ;",
    "- copyDirections = tableau de libelles de directions en copie ;",
    "- emitterDirection = un seul libelle de direction ou service emetteur deduit ;",
    "Limites de sortie : summary <= 240 caracteres ; keywords <= 8 elements ; signers <= 6 elements.",
    "Si plusieurs hypotheses existent, choisir la plus prudente et diminuer confidenceScore."
  ].join("\n");
}
